name: Build PLC project with Github-managed runner (using a Windows Container)

on:
  push:
    branches:
      - main

jobs:
  custom-build-job:
    runs-on: windows-2022

    steps:
      - name: Check Docker Cache
        id: cache-docker
        uses: actions/cache@v3
        with:
          path: C:\docker-cache\bnr-as412.tar
          key: docker-image-musserautomation-bnr-as412

      - name: Load Docker Image from Cache
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: docker load -i C:\docker-cache\bnr-as412.tar

      - name: Pull Docker Image (if not cached)
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          mkdir C:\docker-cache
          docker pull musserautomation/bnr-as412
          docker save -o C:\docker-cache\bnr-as412.tar musserautomation/bnr-as412

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: CustomRepoFolder

      - name: Run the build process inside the container
        run: |
          docker run --rm `
            -v "${{ github.workspace }}:C:\workspace" `
            musserautomation/bnr-as412 `
            powershell -Command "& 'C:\BrAutomation\AS412\bin-en\BR.AS.Build.exe' 'C:\workspace\CustomRepoFolder\BuildServer.apj' -c 'Simulator' -buildMode 'Build'"
