name: Build PLC project with Github-managed runner (using a Windows Container)

on:
  push:
    branches:
      - main

jobs:
  custom-build-job:
    runs-on: windows-2022

    services:
      bnr_as412:
        image: musserautomation/bnr-as412
        options: --name bnr_as412_container

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: CustomRepoFolder

      - name: Run the build process inside the container
        run: |
          docker exec bnr_as412_container powershell -Command "& 'C:\BrAutomation\AS412\bin-en\BR.AS.Build.exe' 'C:\workspace\CustomRepoFolder\BuildServer.apj' -c 'Simulator' -buildMode 'Build'"
