name: Build PLC project with Github-managed runner (using a Windows Container)

on:
  push:
    branches:
      - main

jobs:
  custom-build-job:
    runs-on: windows-2022

    steps:
      - name: Pull the Docker image
        run: docker pull musserautomation/bnr-as412
            
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: CustomRepoFolder

      - name: Run the container and execute the build process
        run: |
          docker run --rm `
            --name bnr_as412_container `
            -v "${{ github.workspace }}:C:\workspace" `
            musserautomation/bnr-as412 `
            powershell -Command "& 'C:\BrAutomation\AS412\bin-en\BR.AS.Build.exe' 'C:\workspace\CustomRepoFolder\BuildServer.apj' -c 'Simulator' -buildMode 'Build'"

      - name: Show logs if the build fails
        if: failure()
        run: docker logs bnr_as412_container
